Refactor models and views for Benny Chat
Esquire-gh/AI-Study-Buddy pull request #4
Opened 2024-09-18 13:20 UTC by NKETIAH53

2024-09-18 17:34 UTC, Esquire-gh commented on chat/models.py
> +    modified_at = models.DateTimeField(auto_now=True)
convert created_at and modified_at to an abstract class that all models that need it can use

2024-09-18 17:36 UTC, Esquire-gh commented on chat/static/css/main.css
> +    display: flex;
why is there a need for frontend changes?

2024-09-18 17:42 UTC, Esquire-gh requested changes
- The PR should have only one mirgration file with all the changes. Almos like we're starting from scratch.

- Remove the entire frontend file uploads. and the supporting endpoints. File uploads will only happen in the admin or through a the scraper script. So for now remove the frontend implementation and setup a flow for using the admin to load files and triggering the index build.

2024-09-19 14:36 UTC, Esquire-gh commented on chat/models.py
>          self.indexed_file_ids = str(json.dumps([file.id for file in files]))
fix this line, if the the module already has some indexed files, this will replace them. instead, you must update it and make sure ids are unique

2024-09-19 15:16 UTC, Esquire-gh commented on chat/models.py
>          self.indexed_file_ids = str(json.dumps([file.id for file in files]))
Also, put a screenshot of the current UI in the description for me.

2024-09-19 16:17 UTC, NKETIAH53 commented on chat/models.py
>          self.indexed_file_ids = str(json.dumps([file.id for file in files]))
![Screenshot from 2024-09-19 16-11-20](https://github.com/user-attachments/assets/48824432-adc4-49ac-9b19-b776219b6762)


![Screenshot from 2024-09-19 16-10-49](https://github.com/user-attachments/assets/d269804e-7282-435b-a0b5-31c071cc4fca)

2024-09-19 16:57 UTC, Esquire-gh approved these changes

2024-09-19 16:58 UTC, merged